### ISSUE TITLE
Having issues getting react-native running

### ISSUE THREAD

**Issue by jocubeit** [gauravtiwari/graphql-blog-mobile#1]
Following the instructions I'm finding I'm missing dependencies in the node_modules directory, like node_modules/react/lib/ReactComponentTreeDevtool.js, node_modules/react/lib/ReactNativeBridgeEventPlugin.js, etc. As a result the React Packager terminates prematurely, and then the iOS Simulator fails because it can't connect to the server. Any clues how I might fix this?

I have no problem creating a new react-native project and starting it. Running react-native-cli: 1.0.0
and react-native: 0.26.2.

**Comment by gauravtiwari** [comment]
Hey @JurgenJocubeit There are some issues with React-native, especially with duplication of node_modules as it exist in both react and react-native. These issues seems to be resolved lately after `0.26.0` version. I have no problem running this repo, with `0.26.0.rc`. 

For development server issue, please make sure you run the `relay-rails-blog` repo first so that you have GraphQL server running and then just run: `react-native run-ios --reset-cache`

**Comment by gauravtiwari** [comment]
Btw, I just applied `npm shrinkwrap` to lock the deps. Please `rm -rf the node_modules` followed by, pulling latest changes from master and then running `npm install` to reinstall deps. And finally, run: `react-native run-ios --reset-cache`

If you see red screen with can't not connect to dev server on simulator, please hit `cmd+R` to refresh (this happens because simulator starts before the application is built)

**Comment by gauravtiwari** [comment]
Also, updated the Readme, guess it wasn't very clear how to setup and run the app.

**Comment by jocubeit** [comment]
![capto_capture 2016-06-16_11-50-42_am](https://cloud.githubusercontent.com/assets/209968/16103146/3f02f6d4-33b9-11e6-9755-967acac1743f.png)

Followed your instructions the got the following screen after starting again.

I then followed these screens instructions and it's all working.

Thanks very much for your help, and for sharing your knowledge and code, very much appreciated.

**Comment by gauravtiwari** [comment]
Awesome :) Yes, forgot about the `watchman`. This is a very basic app that explores GraphQL with React native so, if you want to play around or add something, feel free to submit a PR.

Thank you :)
